### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by kruthikakr** [valayDave/arxiv-miner#8]
Hi

I am trying to set up and explore this code. I found the pip install -r git+https://github.com/valayDave/arxiv-miner doesn't work . Also 
sh cso_setup.sh  giving the error 
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'nltk'
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
AttributeError: module 'classifier.classifier' has no attribute 'setup'

**Comment by valayDave** [comment]
Thanks for opening this issue.  I have fixed the documentation problem for installing `arxiv-miner`. You can check [here](https://github.com/valayDave/arxiv-miner/blob/master/docs/quickstart.md#core-library-install). The `-r` was the problem. 

The [cso_setup.sh](https://github.com/valayDave/arxiv-miner/blob/master/cso_setup.sh) has been modified to ensure the CSO installation doesn't fail.
